---

- name: Prepare for configuration build
  hosts: all
  tasks:
  - file: path={{build_dir}} state=absent
    changed_when: no
    check_mode: no
    run_once: yes
    tags: [ clean ]
  - file: path={{build_dir}}/{{inventory_hostname}} state=directory
    changed_when: no
    check_mode: no
    tags: [ always ]

- name: Generate configurations
  hosts: ios
  tags: [ build ]
  roles:
    - base
